// Generated from CRADI-mobile lib/core/data/mvp_locations_data.dart — keep in sync.
export const LGAS: readonly string[] = [
    'Ado',
    'Agatu',
    'Akwanga',
    'Apa',
    'Awe',
    'Barkin Ladi',
    'Bassa',
    'Bokkos',
    'Buruku',
    'Doma',
    'Gboko',
    'Guma',
    'Gwer East',
    'Gwer West',
    'Jos East',
    'Jos North',
    'Jos South',
    'Kanam',
    'Kanke',
    'Karu',
    'Katsina-Ala',
    'Keana',
    'Keffi',
    'Kokona',
    'Konshisha',
    'Kwande',
    'Lafia',
    'Langtang North',
    'Langtang South',
    'Logo',
    'Makurdi',
    'Mangu',
    'Mikang',
    'Nasarawa',
    'Nasarawa Egon',
    'Obi',
    'Ogbadibo',
    'Ohimini',
    'Oju',
    'Okpokwu',
    'Oturkpo',
    'Pankshin',
    'Riyom',
    'Shendam',
    'Tarka',
    'Toto',
    'Ukum',
    'Ushongo',
    'Vandeikya',
    'Wamba',
    'Wase',
] as const;
