// Generated from CRADI-mobile lib/core/data/mvp_locations_data.dart — keep in sync.
// 53 LGAs, 584 wards (INEC electoral wards).

export interface LgaWards {
    state: string;
    lga: string;
    wards: readonly string[];
}

export const LOCATIONS: readonly LgaWards[] = [
    {
        state: 'Benue',
        lga: 'Ado',
        wards: [
            'Akpoge/Ogbilolo',
            'Apa',
            'Ekile',
            'Igumale I',
            'Igumale II',
            'Ijigban',
            'Ogege',
            'Royongo',
            'Ukwonyo',
            'Ulayi',
        ],
    },
    {
        state: 'Benue',
        lga: 'Agatu',
        wards: [
            'Enungba',
            'Obagaji',
            'Odugbeho',
            'Ogbaulu',
            'Ogwule Kaduna',
            'Ogwule Ogbaulu',
            'Okokolo',
            'Oshigbudu',
            'Usha',
        ],
    },
    {
        state: 'Benue',
        lga: 'Apa',
        wards: [
            'Apa Ward',
            'Igah Ward',
            'Oiji Ward',
            'Edikwu Ward',
            'Auke Ward',
            'Ugbokpo Ward',
            'Icho Ward',
            'Apa Central Ward',
            'Apa North Ward',
            'Apa South Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Buruku',
        wards: [
            'Binev',
            'Etulo',
            'Mbaade',
            'Mbaakura',
            'Mbaapen',
            'Mbaatirkyaa',
            'Mbaazagee',
            'Mbaikyongo/nyifon',
            'Mbaityough',
            'Mbakyaan',
            'Mbaya',
            'Mbayaka',
            'Shorov',
        ],
    },
    {
        state: 'Benue',
        lga: 'Gboko',
        wards: [
            'Gboko Central',
            'Gboko North',
            'Gboko South',
            'Gboko East',
            'Gboko West',
            'Yandev North',
            'Yandev South',
            'Mbasombo',
            'Ikyurav-Ye',
            'Igyorov',
            'Mbadwem',
        ],
    },
    {
        state: 'Benue',
        lga: 'Guma',
        wards: [
            'Guma Ward',
            'Kaambe Ward',
            'Saghev Ward',
            'Uvir Ward',
            'Abinsi Ward',
            'Nyiev Ward',
            'Mutsu Ward',
            'Gbemacha Ward',
            'Pepe Ward',
            'Waya Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Gwer East',
        wards: [
            'Aliade Central',
            'Aliade North',
            'Aliade South',
            'Mbadim Ward',
            'Ikyogbajir Ward',
            'Ikpayongo Ward',
            'Agaishie Ward',
            'Gbemacha Ward',
            'Ulayi Ward',
            'Imande Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Gwer West',
        wards: [
            'Naka Central',
            'Naka East',
            'Naka West',
            'Sengev Ward',
            'Gbaange Ward',
            'Saghev Ward',
            'Mbapa Ward',
            'Ikyonov Ward',
            'Tarka Ward',
            'Bar Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Katsina-Ala',
        wards: [
            'Katsina-Ala Town',
            'Gbise Ward',
            'Ikyurav-Tiev Ward',
            'Tongov Ward',
            'Utange Ward',
            'Yooyo Ward',
            'Michihe Ward',
            'Katsina-Ala East',
            'Katsina-Ala West',
            'Mbayion Ward',
            'Ihugh Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Konshisha',
        wards: [
            'Tse-Agberagba',
            'Mbakyaan Ward',
            'Mbaikyongo Ward',
            'Mbatse Ward',
            'Konshisha Central',
            'Tse-Agee Ward',
            'Mbayenge Ward',
            'Mbaiase Ward',
            'Tse-Mbaighil Ward',
            'Shitile Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Kwande',
        wards: [
            'Adikpo Central',
            'Adikpo North',
            'Adikpo South',
            'Turan Ward',
            'Nanev Ward',
            'Jiir Ward',
            'Yaav Ward',
            'Shangev-Ya Ward',
            'Tondov Ward',
            'Mbayar Ward',
            'Kwande East',
        ],
    },
    {
        state: 'Benue',
        lga: 'Logo',
        wards: [
            'Ugba Ward',
            'Tombo Ward',
            'Ukemberagya Ward',
            'Anyiin Ward',
            'Logo Ward',
            'Nzorov Ward',
            'Turan Ward',
            'Gaambe-Ushin Ward',
            'Yogbo Ward',
            'Ayilamo Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Makurdi',
        wards: [
            'Agan',
            'Ankpa/Wadata',
            'Bar',
            'Central/South Mission',
            'Clerks/Market',
            'Fiidi',
            'Mbalagh',
            'Modern Market',
            'North Bank I',
            'North Bank II',
            'Wailomayo',
        ],
    },
    {
        state: 'Benue',
        lga: 'Obi',
        wards: [
            'Obi Ward',
            'Oju Ward',
            'Ito Ward',
            'Orihi Ward',
            'Adum Ward',
            'Aloja Ward',
            'Ohimini Ward',
            'Igede Ward',
            'Obarike Ward',
            'Oju Central',
        ],
    },
    {
        state: 'Benue',
        lga: 'Ogbadibo',
        wards: [
            'Otukpa Central',
            'Otukpa North',
            'Otukpa South',
            'Okpoga Ward',
            'Orokam Ward',
            'Ai-Ome Ward',
            'Ogbadibo East',
            'Ogbadibo West',
            'Itabono Ward',
            'Ehaje Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Ohimini',
        wards: [
            'Ochobo Ward',
            'Oglewu Ward',
            'Onyagede Ward',
            'Idah-Apa Ward',
            'Ohimini Central',
            'Ehaje Ward',
            'Adoka Ward',
            'Ogbabede Ward',
            'Orokam Ward',
            'Onyagede East',
        ],
    },
    {
        state: 'Benue',
        lga: 'Oju',
        wards: [
            'Oju Central',
            'Obarike-Ito Ward',
            'Afo Ward',
            'Igede Ward',
            'Ukwonyo Ward',
            'Oju North',
            'Oju South',
            'Oju East',
            'Oju West',
            'Abocho Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Okpokwu',
        wards: [
            'Ichama Ward',
            'Edumoga Ward',
            'Eke-Oitobi Ward',
            'Ogwule-Ogbaulu Ward',
            'Okpokwu Central',
            'Okpoga Ward',
            'Ugbokolo Ward',
            'Edikwu Ward',
            'Okpokwu East',
            'Okpokwu West',
        ],
    },
    {
        state: 'Benue',
        lga: 'Oturkpo',
        wards: [
            'Oturkpo Central',
            'Oturkpo North',
            'Oturkpo South',
            'Ugbokolo Ward',
            'Adoka Ward',
            'Ogene Ward',
            'Okete Ward',
            'Ewulo Ward',
            'Oturkpo East',
            'Oturkpo West',
            'Akpete Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Tarka',
        wards: [
            'Wannune Central',
            'Wannune North',
            'Wannune South',
            'Utange Ward',
            'Ugbaam Ward',
            'Mbayar Ward',
            'Tarka Ward',
            'Lessel Ward',
            'Nanev Ward',
            'Mbadwem Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Ukum',
        wards: [
            'Ugondo Ward',
            'Mbacher Ward',
            'Kendev Ward',
            'Luhutu Ward',
            'Ukum Central',
            'Ikyurav Ukum',
            'Mbatya Ward',
            'Sankera Ward',
            'Borikyo Ward',
            'Uikpam Ward',
            'Zaki-Biam Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Ushongo',
        wards: [
            'Lessel Ward',
            'Ikparev Ward',
            'Mbatyough Ward',
            'Mbadwem Ward',
            'Ushongo Central',
            'Mbatyav Ward',
            'Ushongo North',
            'Ushongo South',
            'Ugbema Ward',
            'Korinya Ward',
        ],
    },
    {
        state: 'Benue',
        lga: 'Vandeikya',
        wards: [
            'Vandeikya Central',
            'Vandeikya North',
            'Vandeikya South',
            'Mbadede Ward',
            'Tsambe Ward',
            'Mbakyaan Ward',
            'Mbatser Ward',
            'Vandeikya East',
            'Vandeikya West',
            'Tse-Ugba Ward',
            'Kpa-ver Ward',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Akwanga',
        wards: [
            'Anchobaba',
            'Agyaga',
            'Gwanje Gwanje',
            'Ancho Nighaan',
            'Andaha',
            'Akwanga Central',
            'Akwanga North',
            'Akwanga South',
            'Arikya',
            'Ningo',
            'Wamba',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Awe',
        wards: [
            'Madaki',
            'Galadima',
            'Jangaru',
            'Kanje Abuni',
            'Ribi',
            'Awe Central',
            'Keana',
            'Obi',
            'Tudun Fulani',
            'Daddere',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Doma',
        wards: [
            'Rukubi',
            'Agbashi',
            'Doka',
            'Alagye',
            'Akpanaja',
            'Madaki',
            'Ungwan Sarki Dawaki',
            'Madauchi',
            'Ungwan Dan Galadima',
            'Sabon Gari',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Karu',
        wards: [
            'Aso/Kodape',
            'Agada/Bagaji',
            'Karshi I',
            'Karshi II',
            'Kafin Shanu/Betti',
            'Tattara/Kondoro',
            'Gitata',
            'Gurku/Kabusu',
            'Uke',
            'Panda/Kare',
            'Karu',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Keana',
        wards: [
            'Iswagu',
            'Amiri',
            'Obene',
            'Oki',
            'Keana Central',
            'Aloshi',
            'Giza',
            'Obi',
            'Agaza',
            'Mada',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Keffi',
        wards: [
            'Angwan Iya I',
            'Angwan Iya II',
            'Tudun Kofa TV',
            'Gangare Tudu',
            'Keffi Central',
            'Keffi North',
            'Keffi South',
            'Sabon Gari',
            'Angwan Jaba',
            'Liman Abaji',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Kokona',
        wards: [
            'Agwada',
            'Koya/Kana',
            'Bassa',
            'Kokona',
            'Gurku',
            'Garaku',
            'Agaza',
            'Nieshi',
            'Gadabuke',
            'Ninkoro',
            'Garaku East',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Lafia',
        wards: [
            'Adogi',
            'Agyaragun Tofa',
            'Bakin Rijiya/Akurba',
            'Arikya',
            'Lafia Central',
            'Lafia East',
            'Lafia West',
            'Lafia North',
            'Lafia South',
            'Shabu',
            'Doma Road',
            'Makurdi Road',
            'New Layout',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Nasarawa',
        wards: [
            'Udenin Gida',
            'Akum',
            'Udenin',
            'Loko',
            'Tunga/Bakono',
            'Guto/Aisa',
            'Nasarawa North',
            'Nasarawa East',
            'Nasarawa Central',
            'Nasarawa Main Town',
            'Ara I',
            'Ara II',
            'Laminga',
            'Kanah/Ondo/Apawu',
            'Odu',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Nasarawa Egon',
        wards: [
            'Nasarawa Eggon',
            'Ubbe',
            'Igga/Burumburum',
            'Umme',
            'Mada Station',
            'Lizzin Keffi/Ezzen',
            'Lambaga/Arikpa',
            'Kagbu Wana',
            'Ikka Wangibi',
            'Ende',
            'Wakama',
            'Aloce/Ginda',
            'Alogani',
            'Agunji',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Obi',
        wards: [
            'Agwatashi',
            'Deddere/Riri',
            'Duduguru',
            'Gwadenye',
            'Kyakale',
            'Gidan Ausa I',
            'Gidan Ausa II',
            'Adudu',
            'Agwada',
            'Riri',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Toto',
        wards: [
            'Gwagwada',
            'Gadagwa',
            'Bugakarmo',
            'Umaisha',
            'Toto Central',
            'Gade',
            'Gadabuke',
            'Kwara',
            'Dausu',
            'Toto East',
            'Toto West',
            'Umaisha North',
        ],
    },
    {
        state: 'Nasarawa',
        lga: 'Wamba',
        wards: [
            'Konvan',
            'Wayo',
            'Wamba East',
            'Wamba West',
            'Arikya',
            'Jangwa',
            'Kwara',
            'Gitata',
            'Wamba Central',
            'Wamba North',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Bokkos',
        wards: [
            'Bokkos',
            'Butura',
            'Daffo',
            'Dorpshiri',
            'Mushere',
            'Richa',
            'Toff',
            'Sha',
            'Manguna',
            'Kamboa',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Barkin Ladi',
        wards: [
            'Barkin Ladi',
            'Gassa Sho',
            'Gindin Akwati',
            'Foron',
            'Gwol',
            'Kuru',
            'Fan',
            'Heipang',
            'Ropp',
            'Shen',
            'Bisichi',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Bassa',
        wards: [
            'Kishika',
            'Bassa',
            'Kwall',
            'Miango',
            'Rukuba',
            'Jengre',
            'Zawan',
            'Sha',
            'Rafin Bauna',
            'Buji',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Jos East',
        wards: [
            'Federe',
            'Fobur A',
            'Fobur B',
            'Angware',
            'Dadin Kowa',
            'Fursum',
            'Marama',
            'Tilden Fulani',
            'Shere',
            'Kwang',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Jos North',
        wards: [
            'Abba Na Shehu',
            'Ali Kazaure',
            'Gangare',
            'Garba Daho',
            'Ibrahim Katsina',
            'Jenta Adamu',
            'Jenta Apata',
            'Jos Jarawa',
            'Naraguta A',
            'Naraguta B',
            'Sarkin Arab',
            'Tafawa Balewa',
            'Tudun Wada - Kabong',
            'Vanderpuye',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Jos South',
        wards: [
            'Bukuru',
            'Du',
            'Giring',
            'Gyel A',
            'Gyel B',
            'Kuru A',
            'Kuru B',
            'Shen',
            'Turu',
            'Vwang',
            'Zawan A',
            'Zawan B',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Kanam',
        wards: [
            'Birbyang',
            'Dengi',
            'Dugub',
            'Gagdib',
            'Garga',
            'Gumsher',
            'Gwamlar',
            'Jarmai',
            'Jom',
            'Kanam',
            'Kantana',
            'Kunkyam',
            'Munbutbo',
            'Kampani',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Kanke',
        wards: [
            'Ampang East A',
            'Ampang East B',
            'Amper Chika A',
            'Amper Chika B',
            'Kanke',
            'Amper',
            'Kembo',
            'Kwalla',
            'Pil',
            'Kabwir',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Langtang North',
        wards: [
            'Jat',
            'Keller',
            'Kuffen',
            'Langtang North Central',
            'Gazum',
            'Mabudi',
            'Pil Gani',
            'Yelwa',
            'Timbol',
            'Garkawa',
            'Tahoss',
            'Langkuk',
            'Fursum',
            'Dadiya',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Langtang South',
        wards: [
            'Gamaka',
            'Lashel',
            'Mabudi',
            'Jemkur',
            'Turaki',
            'Langtang South',
            'Piapung',
            'Mbar',
            'Ying',
            'Buki',
            'Gazum',
            'Kwallak',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Mangu',
        wards: [
            'Chanso',
            'Gindiri I',
            'Gindiri II',
            'Kasuwan Ali',
            'Mangu',
            'Ampang West',
            'Ampang East',
            'Kombun',
            'Langshi',
            'Chakwas',
            'Jipul',
            'Kerang',
            'Mabudi',
            'Panyam',
            'Pushit',
            'Wanka',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Mikang',
        wards: [
            'Garkawa Central',
            'Garkawa North',
            'Garkawa North East',
            'Mikang',
            'Tunkus',
            'Piapung',
            'Tambes',
            'Gupiya',
            'Kasa',
            'Wiaplas',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Pankshin',
        wards: [
            'Chip',
            'Dok Pai',
            'Fier',
            'Mudkang Yelleng',
            'Pankshin Central',
            'Pankshin North',
            'Pankshin South',
            'Kadung',
            'Bwal',
            'Pakain',
            'Tunkus',
            'Kabwir',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Qua\'an Pan',
        wards: [
            'Bwall',
            'Doemak Goechim',
            'Doemak Koplong',
            'Luukwo',
            'Qua\'an Pan',
            'Kwang',
            'Baap',
            'Dokan Tofa',
            'Langas',
            'Namu',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Riyom',
        wards: [
            'Attakar',
            'Bum',
            'Danto',
            'Riyom',
            'Rim',
            'Kassa',
            'Tahoss',
            'Shong',
            'Rafin Bauna',
            'Kwaturu',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Shendam',
        wards: [
            'Derteng',
            'Kalong',
            'Kurungbau A',
            'Shendam',
            'Dokan Kasuwa',
            'Garkep',
            'Kwalla',
            'Panyam',
            'Shendam North',
            'Shendam South',
            'Kurungbau B',
        ],
    },
    {
        state: 'Plateau',
        lga: 'Wase',
        wards: [
            'Bashar',
            'Danbiram',
            'Wase',
            'Gule',
            'Kadarko',
            'Zurak',
            'Lamba',
            'Mavo',
            'Sabon Layi',
            'Wase Central',
            'Wase Tofa',
            'Wayam',
        ],
    },
];

/** States covered, in display order. */
export const STATES: readonly string[] = Array.from(new Set(LOCATIONS.map((l) => l.state)));

/** LGA names in `state`, sorted. */
export function lgasForState(state: string): string[] {
    return LOCATIONS.filter((l) => l.state === state)
        .map((l) => l.lga)
        .sort((a, b) => a.localeCompare(b));
}

/** Wards of `lga` in `state` (LGA names are not unique across states, e.g. Obi), or []. */
export function wardsFor(state: string, lga: string): readonly string[] {
    return LOCATIONS.find((l) => l.state === state && l.lga === lga)?.wards ?? [];
}

/** True when `lga` is an LGA of `state`. */
export function isLgaInState(state: string, lga: string): boolean {
    return LOCATIONS.some((l) => l.state === state && l.lga === lga);
}
